version: '3.8'

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: spotsat
      POSTGRES_PASSWORD: spotsat
      POSTGRES_DB: graph_db
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
